apiVersion: v1
kind: Secret
metadata:
  name: git-auth-github
type: Opaque
stringData:
  .gitconfig: |
    [credential "hostname"]
      helper = store
  .git-credentials: |
    https://myuser:mypass@hostname
